### ISSUE TITLE
Make Aptos startup script idempotent in Tilt

### ISSUE THREAD

**Issue by heyitaki** [wormhole-foundation/wormhole#2265]
Currently, if Aptos encounters an error in Tilt, it will continue to crash loop because the startup will keep erroring when trying to create a resource account that was successfully previously created. Ideally, the startup script should handle such failures so that it can recover from transient issues properly

```
[aptos-contracts] worm aptos deploy-resource <seed> <package-dir>
[aptos-contracts] 
[aptos-contracts] Deploy an Aptos package using a resource account
[aptos-contracts] 
[aptos-contracts] Positionals:
[aptos-contracts]   seed                                                       [string] [required]
[aptos-contracts]   package-dir                                                [string] [required]
[aptos-contracts] 
[aptos-contracts] Options:
[aptos-contracts]       --help             Show help                                     [boolean]
[aptos-contracts]       --version          Show version number                           [boolean]
[aptos-contracts]   -n, --network          network
[aptos-contracts]                    [string] [required] [choices: "mainnet", "testnet", "devnet"]
[aptos-contracts]   -r, --rpc              Override default rpc endpoint url              [string]
[aptos-contracts]       --named-addresses  Named addresses in the format addr1=0x0,addr2=0x1,...
[aptos-contracts]                                                                         [string]
[aptos-contracts] 
[aptos-contracts] Error: Transaction failed: Move abort in 0x1::account: ERESOURCE_ACCCOUNT_EXISTS(0x8000f): An attempt to create a resource account on a claimed account
[aptos-contracts]     at /tmp/clients/js/build/aptos.js:172:19
[aptos-contracts]     at Array.forEach (<anonymous>)
[aptos-contracts]     at callEntryFunc (/tmp/clients/js/build/aptos.js:169:9)
[aptos-contracts]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[aptos-contracts]     at async Object.handler (/tmp/clients/js/build/cmds/aptos.js:155:9)
Detected container restart. Pod: aptos-0. Container: aptos-contracts.
```

**Comment by kcsongor** [comment]
Agreed with would be nice. What do you think is the best way to tackle it @heyitaki ?

**Comment by heyitaki** [comment]
@kcsongor ideally we have some sort of try-catch logic in the `deploy` script for the `worm aptos deploy-resource` commands. I dont think theres any native try catch functionality, but maybe we can run this in a subshell with `set +e` to disregard errors, and exit/handle errors outside of the subshell?

**Comment by kcsongor** [comment]
that's an option, but I worry that doing it that way will swallow genuine deployment errors and make tilt come up clean, which would be a real head scratcher. Probably it would be better to do the try-catch in the typescript and have a flag which returns success when the account already exists, if that makes sense?
