### ISSUE TITLE
tilt ci tests are failing on main

### ISSUE THREAD

**Issue by tbjump** [wormhole-foundation/wormhole#3052]
Here is a PR with no modifications to `main` that is failing tilt tests: https://github.com/wormhole-foundation/wormhole/pull/3050

**Comment by tbjump** [comment]
After restarting it, it succeeded, but a high percentage of runs are still failing. Here are some examples: 

https://github.com/wormhole-foundation/wormhole/actions/runs/5202753200/jobs/9384754173?pr=3054
https://github.com/wormhole-foundation/wormhole/actions/runs/5196028070/jobs/9369333839
https://github.com/wormhole-foundation/wormhole/actions/runs/5202949362/jobs/9385159655?pr=3056
https://github.com/wormhole-foundation/wormhole/actions/runs/5205004596/jobs/9390253755?pr=3055

**Comment by tbjump** [comment]
Another failed run: https://github.com/wormhole-foundation/wormhole/actions/runs/5212809658/jobs/9406925321?pr=3063

**Comment by aadam-10** [comment]
Merged the tickets below into this one

- https://github.com/wormhole-foundation/wormhole/issues/3064
- https://github.com/wormhole-foundation/wormhole/issues/3069

**Comment by tbjump** [comment]
PR https://github.com/wormhole-foundation/wormhole/pull/3096 seems to fix one issue, but there seem to be more, see https://github.com/wormhole-foundation/wormhole/actions/runs/5271914994

Opened https://github.com/wormhole-foundation/wormhole/pull/3097

**Comment by tbjump** [comment]
In [this](https://github.com/wormhole-foundation/wormhole/actions/runs/5279915200/jobs/9551291785?pr=3096) run, there seems to have been an issue with the accountant tests: 

```
2023-06-15T14:20:58.1849470Z accountant-c… │ FAIL __tests__/test_accountant.ts (75.834 s)
2023-06-15T14:20:58.1911721Z accountant-c… │   Global Accountant Tests
2023-06-15T14:20:58.1912477Z accountant-c… │     ✕ Metrics and Contract Queries (60002 ms)
2023-06-15T14:20:58.1913425Z accountant-c… │
2023-06-15T14:20:58.1914188Z accountant-c… │   ● Global Accountant Tests › Metrics and Contract Queries
2023-06-15T14:20:58.1914755Z accountant-c… │
2023-06-15T14:20:58.1915630Z accountant-c… │     thrown: "Exceeded timeout of 60000 ms for a test.
2023-06-15T14:20:58.1916699Z accountant-c… │     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
2023-06-15T14:20:58.1917860Z accountant-c… │
2023-06-15T14:20:58.1918337Z accountant-c… │       153 |
2023-06-15T14:20:58.1918985Z accountant-c… │       154 | describe("Global Accountant Tests", () => {
2023-06-15T14:20:58.1919690Z accountant-c… │     > 155 |   test("Metrics and Contract Queries", async () => {
2023-06-15T14:20:58.1920721Z accountant-c… │           |       ^
2023-06-15T14:20:58.1921367Z accountant-c… │       156 |     let attestedAddress = "";
2023-06-15T14:20:58.1921956Z accountant-c… │       157 |     //
2023-06-15T14:20:58.1922696Z accountant-c… │       158 |     // STEP 0 - attest the token
2023-06-15T14:20:58.1974926Z accountant-c… │
2023-06-15T14:20:58.1976755Z accountant-c… │       at __tests__/test_accountant.ts:155:7
2023-06-15T14:20:58.1978199Z accountant-c… │       at Object.<anonymous> (__tests__/test_accountant.ts:154:9)
2023-06-15T14:20:58.1979079Z accountant-c… │
2023-06-15T14:20:58.1979683Z accountant-c… │ Test Suites: 1 failed, 1 total
2023-06-15T14:20:58.1980492Z accountant-c… │ Tests:       1 failed, 1 total
2023-06-15T14:20:58.1981084Z accountant-c… │ Snapshots:   0 total
2023-06-15T14:20:58.1981611Z accountant-c… │ Time:        75.912 s
```

**Comment by tbjump** [comment]
Re-running the above succeded. I'll make a separate issue to investigate the flaky accountant test: https://github.com/wormhole-foundation/wormhole/issues/3099
