### ISSUE TITLE
ci: Accountant tests in Tilt are flaky

### ISSUE THREAD

**Issue by tbjump** [wormhole-foundation/wormhole#3099]
In [this](https://github.com/wormhole-foundation/wormhole/actions/runs/5279915200/jobs/9551291785?pr=3096) run, there seems to have been an issue with the accountant tests: 

```
2023-06-15T14:20:58.1849470Z accountant-c… │ FAIL __tests__/test_accountant.ts (75.834 s)
2023-06-15T14:20:58.1911721Z accountant-c… │   Global Accountant Tests
2023-06-15T14:20:58.1912477Z accountant-c… │     ✕ Metrics and Contract Queries (60002 ms)
2023-06-15T14:20:58.1913425Z accountant-c… │
2023-06-15T14:20:58.1914188Z accountant-c… │   ● Global Accountant Tests › Metrics and Contract Queries
2023-06-15T14:20:58.1914755Z accountant-c… │
2023-06-15T14:20:58.1915630Z accountant-c… │     thrown: "Exceeded timeout of 60000 ms for a test.
2023-06-15T14:20:58.1916699Z accountant-c… │     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
2023-06-15T14:20:58.1917860Z accountant-c… │
2023-06-15T14:20:58.1918337Z accountant-c… │       153 |
2023-06-15T14:20:58.1918985Z accountant-c… │       154 | describe("Global Accountant Tests", () => {
2023-06-15T14:20:58.1919690Z accountant-c… │     > 155 |   test("Metrics and Contract Queries", async () => {
2023-06-15T14:20:58.1920721Z accountant-c… │           |       ^
2023-06-15T14:20:58.1921367Z accountant-c… │       156 |     let attestedAddress = "";
2023-06-15T14:20:58.1921956Z accountant-c… │       157 |     //
2023-06-15T14:20:58.1922696Z accountant-c… │       158 |     // STEP 0 - attest the token
2023-06-15T14:20:58.1974926Z accountant-c… │
2023-06-15T14:20:58.1976755Z accountant-c… │       at __tests__/test_accountant.ts:155:7
2023-06-15T14:20:58.1978199Z accountant-c… │       at Object.<anonymous> (__tests__/test_accountant.ts:154:9)
2023-06-15T14:20:58.1979079Z accountant-c… │
2023-06-15T14:20:58.1979683Z accountant-c… │ Test Suites: 1 failed, 1 total
2023-06-15T14:20:58.1980492Z accountant-c… │ Tests:       1 failed, 1 total
2023-06-15T14:20:58.1981084Z accountant-c… │ Snapshots:   0 total
2023-06-15T14:20:58.1981611Z accountant-c… │ Time:        75.912 s
```

Re-running it in https://github.com/wormhole-foundation/wormhole/actions/runs/5279915200/jobs/9553215677?pr=3096 made it go through.

**Comment by tbjump** [comment]
Two more failed runs: 
https://github.com/wormhole-foundation/wormhole/actions/runs/5282835446/jobs/9558812162
https://github.com/wormhole-foundation/wormhole/actions/runs/5282835446/attempts/1

**Comment by tbjump** [comment]
Seems to be solved by https://github.com/wormhole-foundation/wormhole/pull/3096
