### ISSUE TITLE
solana jsonrpc crash encountered by a v2 guardian

### ISSUE THREAD

**Issue by leoluk** [wormhole-foundation/wormhole#375]
```
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: 2021-09-02T15:52:57.030+0300#011INFO#011wormhole.root.terrawatch#011terra/watcher.go:119#011subscribed to new transaction events
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: 2021-09-02T15:52:57.115+0300#011INFO#011wormhole.root.p2p#011p2p/p2p.go:174#011Connected to bootstrap peers#011{"num": 1}
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: panic: runtime error: invalid memory address or nil pointer dereference
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xf10d9d]
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: goroutine 202 [running]:
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: github.com/gagliardetto/solana-go/rpc/jsonrpc.(*rpcClient).doCall(0xc0000a1ec0, 0x1d2b260, 0xc002da31a0, 0xc002dba880, 0x0, 0x0, 0x0)
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: #011/opt/wormhole/go/pkg/mod/github.com/certusone/solana-go@v0.3.7-0.20210729105530-67b495e4e529/rpc/jsonrpc/jsonrpc.go:430 +0xd5d
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: github.com/gagliardetto/solana-go/rpc/jsonrpc.(*rpcClient).CallForInto(0xc0000a1ec0, 0x1d2b260, 0xc002da31a0, 0x15d7e60, 0xc002cf9300, 0x18e33c9, 0x7, 0xc002e1d3b0, 0x1, 0x1, ...)
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: #011/opt/wormhole/go/pkg/mod/github.com/certusone/solana-go@v0.3.7-0.20210729105530-67b495e4e529/rpc/jsonrpc/jsonrpc.go:352 +0xa5
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: github.com/gagliardetto/solana-go/rpc.(*Client).GetSlot(0xc00c5a3290, 0x1d2b260, 0xc002da31a0, 0x18e5d22, 0x9, 0xc002e1d390, 0x0, 0x1)
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: #011/opt/wormhole/go/pkg/mod/github.com/certusone/solana-go@v0.3.7-0.20210729105530-67b495e4e529/rpc/getSlot.go:30 +0xc2
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: github.com/certusone/wormhole/bridge/pkg/solana.(*SolanaWatcher).Run.func1(0x1d2b1f0, 0xc001cbc580, 0xc0000d9f10, 0xc001e16d80, 0xc001e2e850, 0xc001e2c4e0, 0x2b)
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: #011/opt/wormhole/wormhole/bridge/pkg/solana/client.go:133 +0x277
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: created by github.com/certusone/wormhole/bridge/pkg/solana.(*SolanaWatcher).Run
Sep  2 15:52:57 m2-wormholeV2-01 guardiand[1203]: #011/opt/wormhole/wormhole/bridge/pkg/solana/client.go:120 +0x1a6
Sep  2 15:52:58 m2-wormholeV2-01 systemd[1]: guardiand.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep  2 15:52:58 m2-wormholeV2-01 systemd[1]: guardiand.service: Failed with result 'exit-code'.
```

**Comment by aadam-10** [comment]
Please reopen if this is still relevant
